#! /usr/local/env python

from wafbuildutils import wafbuildutils

DEFINES = \
[
	"HLBSP",
	"DOUBLEVEC_T"
]

def options(ctx):
	pass

def configure(ctx):
	ctx.env.append_unique("DEFINES", DEFINES)

def build(bld):
	bld.load_envs()
	bld.env = bld.all_envs[wafbuildutils.get_subproject_name(bld)]

	parent = bld.path.find_node("..")
	sources = parent.ant_glob("common/*.cpp")
	sources += bld.path.ant_glob("*.cpp")

	# idx needs to be set to avoid object files being overwritten by parallel compilations
	bld.program(source=sources,
				target="abbsp",
				includes=["../template", "../common"],
				idx=2)
